{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c2f12a1-18b4-4924-ab21-3183f8aa3b2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==============================================================\n",
    "# MULTI-CITY AIR QUALITY FORECASTING SYSTEM (GitHub Version)\n",
    "# Delhi | Bangalore | Hualien\n",
    "# Runs daily via GitHub Actions (Free Cloud Automation)\n",
    "# ==============================================================\n",
    "\n",
    "import os\n",
    "import requests\n",
    "import pandas as pd\n",
    "import datetime\n",
    "import numpy as np\n",
    "from sklearn.linear_model import LinearRegression\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ==============================================================\n",
    "# 1️ CONFIGURATION\n",
    "# ==============================================================\n",
    "\n",
    "CITIES = [\"delhi\", \"bangalore\", \"hualien\"]\n",
    "TOKEN = os.getenv(\"AQICN_TOKEN\", \"639fc5d65c4d0869e99011f0082b1322ed951f76\")\n",
    "\n",
    "BASE_PATH = os.getcwd()\n",
    "KAGGLE_PATH = os.path.join(BASE_PATH, \"data_date.csv\")\n",
    "LIVE_PATH = os.path.join(BASE_PATH, \"air_quality_live_multi.csv\")\n",
    "FORECAST_PATH = os.path.join(BASE_PATH, \"kaggle_forecast.csv\")\n",
    "\n",
    "# ==============================================================\n",
    "# 2️ LOAD KAGGLE DATA\n",
    "# ==============================================================\n",
    "\n",
    "def load_kaggle_data():\n",
    "    try:\n",
    "        df = pd.read_csv(KAGGLE_PATH)\n",
    "        df.rename(columns={\n",
    "            \"Date\": \"timestamp\",\n",
    "            \"Country\": \"country\",\n",
    "            \"Status\": \"status\",\n",
    "            \"AQI Value\": \"aqi\"\n",
    "        }, inplace=True)\n",
    "        df[\"timestamp\"] = pd.to_datetime(df[\"timestamp\"], errors=\"coerce\")\n",
    "        df = df.dropna(subset=[\"aqi\"])\n",
    "        df = df.sort_values(\"timestamp\")\n",
    "        print(f\"✅ Loaded Kaggle dataset with {len(df)} records.\")\n",
    "        return df\n",
    "    except FileNotFoundError:\n",
    "        print(f\" Kaggle dataset not found at {KAGGLE_PATH}\")\n",
    "        return pd.DataFrame()\n",
    "\n",
    "# ==============================================================\n",
    "# 3️ FETCH LIVE AQI (for all cities)\n",
    "# ==============================================================\n",
    "\n",
    "def get_live_aqi(city):\n",
    "    url = f\"http://api.waqi.info/feed/{city}/?token={TOKEN}\"\n",
    "    try:\n",
    "        r = requests.get(url, timeout=10)\n",
    "        data = r.json()\n",
    "    except Exception as e:\n",
    "        print(f\" Error fetching {city}: {e}\")\n",
    "        return None\n",
    "\n",
    "    if data.get(\"status\") != \"ok\":\n",
    "        print(f\" API error for {city}: {data}\")\n",
    "        return None\n",
    "\n",
    "    d = data[\"data\"]\n",
    "    iaqi = d.get(\"iaqi\", {})\n",
    "    record = {\n",
    "        \"city\": city.capitalize(),\n",
    "        \"timestamp\": d[\"time\"][\"s\"],\n",
    "        \"aqi\": d[\"aqi\"],\n",
    "        \"pm25\": iaqi.get(\"pm25\", {}).get(\"v\", None),\n",
    "        \"pm10\": iaqi.get(\"pm10\", {}).get(\"v\", None),\n",
    "        \"no2\": iaqi.get(\"no2\", {}).get(\"v\", None),\n",
    "        \"so2\": iaqi.get(\"so2\", {}).get(\"v\", None),\n",
    "        \"co\": iaqi.get(\"co\", {}).get(\"v\", None),\n",
    "        \"o3\": iaqi.get(\"o3\", {}).get(\"v\", None)\n",
    "    }\n",
    "    print(f\" Live AQI fetched for {city.capitalize()}: AQI={record['aqi']}\")\n",
    "    return record\n",
    "\n",
    "\n",
    "def append_live_data():\n",
    "    all_records = []\n",
    "    for city in CITIES:\n",
    "        rec = get_live_aqi(city)\n",
    "        if rec:\n",
    "            all_records.append(rec)\n",
    "    if not all_records:\n",
    "        print(\" No live data collected.\")\n",
    "        return\n",
    "\n",
    "    df = pd.DataFrame(all_records)\n",
    "    try:\n",
    "        existing = pd.read_csv(LIVE_PATH)\n",
    "        updated = pd.concat([existing, df], ignore_index=True)\n",
    "    except FileNotFoundError:\n",
    "        updated = df\n",
    "\n",
    "    updated.drop_duplicates(subset=[\"timestamp\", \"city\"], keep=\"last\", inplace=True)\n",
    "    updated.to_csv(LIVE_PATH, index=False)\n",
    "    print(f\"Live data updated for {len(CITIES)} cities.\")\n",
    "    print(f\" Saved to: {LIVE_PATH}\")\n",
    "\n",
    "# ==============================================================\n",
    "# 4️⃣ KAGGLE-BASED FORECAST (General Trend)\n",
    "# ==============================================================\n",
    "\n",
    "def train_kaggle_regression(df):\n",
    "    if df.empty:\n",
    "        print(\" Kaggle dataset is empty. Skipping forecast.\")\n",
    "        return\n",
    "\n",
    "    df = df.dropna(subset=[\"aqi\", \"timestamp\"])\n",
    "    df[\"timestamp\"] = pd.to_datetime(df[\"timestamp\"], errors=\"coerce\")\n",
    "    df = df.sort_values(\"timestamp\")\n",
    "    df[\"day_number\"] = (df[\"timestamp\"] - df[\"timestamp\"].min()).dt.days\n",
    "    if len(df) < 10:\n",
    "        print(\" Not enough Kaggle data to forecast.\")\n",
    "        return\n",
    "\n",
    "    model = LinearRegression()\n",
    "    model.fit(df[[\"day_number\"]], df[\"aqi\"])\n",
    "\n",
    "    future_days = np.arange(df[\"day_number\"].max() + 1, df[\"day_number\"].max() + 8).reshape(-1, 1)\n",
    "    future_preds = model.predict(future_days)\n",
    "    future_dates = [df[\"timestamp\"].max() + datetime.timedelta(days=i) for i in range(1, 8)]\n",
    "\n",
    "    forecast_df = pd.DataFrame({\n",
    "        \"timestamp\": future_dates,\n",
    "        \"Predicted_AQI\": future_preds\n",
    "    })\n",
    "    forecast_df.to_csv(FORECAST_PATH, index=False)\n",
    "    print(\"\\n Next 7-Day Forecast (from Kaggle data):\")\n",
    "    print(forecast_df.head())\n",
    "\n",
    "# ==============================================================\n",
    "# 5️⃣ PER-CITY FORECASTS (based on live data)\n",
    "# ==============================================================\n",
    "\n",
    "def per_city_forecast():\n",
    "    try:\n",
    "        df = pd.read_csv(LIVE_PATH)\n",
    "    except FileNotFoundError:\n",
    "        print(f\" Live data file not found at {LIVE_PATH}\")\n",
    "        return\n",
    "\n",
    "    df[\"timestamp\"] = pd.to_datetime(df[\"timestamp\"], errors=\"coerce\")\n",
    "\n",
    "    print(\"\\n Per-City 7-Day Forecasts (based on live AQI trends):\\n\")\n",
    "    all_forecasts = []\n",
    "\n",
    "    for city in CITIES:\n",
    "        subset = df[df[\"city\"].str.lower() == city].sort_values(\"timestamp\")\n",
    "        if len(subset) < 3:\n",
    "            print(f\" Not enough data for {city.capitalize()}. Need ≥3 records.\")\n",
    "            continue\n",
    "\n",
    "        subset[\"day_number\"] = (subset[\"timestamp\"] - subset[\"timestamp\"].min()).dt.days\n",
    "        X = subset[[\"day_number\"]]\n",
    "        y = subset[\"aqi\"]\n",
    "        model = LinearRegression().fit(X, y)\n",
    "\n",
    "        # Predict next 7 days\n",
    "        future_days = np.arange(subset[\"day_number\"].max() + 1, subset[\"day_number\"].max() + 8).reshape(-1, 1)\n",
    "        preds = model.predict(future_days)\n",
    "        dates = [subset[\"timestamp\"].max() + datetime.timedelta(days=i) for i in range(1, 8)]\n",
    "\n",
    "        forecast_df = pd.DataFrame({\n",
    "            \"City\": city.capitalize(),\n",
    "            \"Date\": dates,\n",
    "            \"Predicted_AQI\": preds\n",
    "        })\n",
    "        all_forecasts.append(forecast_df)\n",
    "\n",
    "        print(f\"\\n📍 {city.capitalize()} Forecast:\")\n",
    "        print(forecast_df.to_string(index=False, formatters={'Predicted_AQI': '{:.1f}'.format}))\n",
    "\n",
    "    if all_forecasts:\n",
    "        result = pd.concat(all_forecasts, ignore_index=True)\n",
    "        result.to_csv(os.path.join(BASE_PATH, \"per_city_forecast.csv\"), index=False)\n",
    "        print(\"\\n All per-city forecasts saved successfully!\")\n",
    "\n",
    "# ==============================================================\n",
    "# 6️⃣ OPTIONAL: PLOT\n",
    "# ==============================================================\n",
    "\n",
    "def generate_forecast_plot():\n",
    "    if not os.path.exists(LIVE_PATH):\n",
    "        return\n",
    "    df = pd.read_csv(LIVE_PATH)\n",
    "    plt.figure(figsize=(10,6))\n",
    "    for city in df['city'].unique():\n",
    "        city_data = df[df['city'] == city]\n",
    "        plt.plot(pd.to_datetime(city_data['timestamp']), city_data['aqi'], label=city)\n",
    "    plt.xlabel(\"Date\")\n",
    "    plt.ylabel(\"AQI\")\n",
    "    plt.title(\"Multi-City AQI Trends\")\n",
    "    plt.legend()\n",
    "    plt.grid(True)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\"forecast_plot.png\")\n",
    "    print(\" Forecast plot saved as forecast_plot.png\")\n",
    "\n",
    "# ==============================================================\n",
    "# 🚀 MAIN EXECUTION\n",
    "# ==============================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    kaggle_df = load_kaggle_data()\n",
    "    append_live_data()\n",
    "    train_kaggle_regression(kaggle_df)\n",
    "    per_city_forecast()\n",
    "    generate_forecast_plot()\n",
    "    print(\"\\n GitHub daily AQI update completed successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "337c1bb1-1361-4bfc-ac4a-41b9fb8a053a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
